### ISSUE TITLE
examples of grammar in world languages

### ISSUE THREAD

**Issue by masterkrang** [masterkrang/kako#12]
i want to compile some different grammars in languages across the world so it's more clear which grammars are complicated, what kind of rule systems there are. this will allow us to easily pick and choose which things are good and leave behind the bad.

**Comment by masterkrang** [comment]
"All languages have regular and irregular grammatical patterns and it's generally easier to learn the grammar of languages with few irregularities, such as Finnish, Turkish and Japanese, than those with more irregular grammar, such as English or Greek."

http://www.omniglot.com/language/grammar.htm

**Comment by ghost** [comment]
There are many grammars in all the languages in the world, as you mentioned. Typological linguists usually research on this quantitatively and qualitatively, but this is a really big field. Here is a brief description of the research: https://en.wikipedia.org/wiki/Linguistic_typology#Quantitative_typology

**Comment by masterkrang** [comment]
@yhdaphne yes, it's a big field, but I believe when the grammar is brought down to it's essence, the formulas should be simple. For example SVO, SOV etc....

**Comment by masterkrang** [comment]
i found a lot of resources for this and commented about them here. since this could be a potentially broad topic i'm going to close this. for now determining a base structure should be fine (in regards to SVO SOV OSV) https://github.com/masterkrang/kako/issues/10#issuecomment-149758871
