### ISSUE TITLE
determine the most used sounds across all languages

### ISSUE THREAD

**Issue by masterkrang** [masterkrang/kako#6]

**Comment by masterkrang** [comment]
Some notes from Jose Ugalde on Quora: 

"I really like your project.
I've done myself some statistical ocurrence analysis of corpora mostly in English, Spanish and Latin. But never something as ambitious as your idea.

To acquire a vast set of corpora for multiple languages, this is what I'd do:
1. Visit the title page of each one of the current International editions of Wikipedia:
   https://en.m.wikipedia.org/wiki/...
   Here's our first problem... most languages are written using a different writing system... Ciryllic script, Chinese ideograms, Greek alphabet, Arabic, Hebrew, etc. You are going to need to find a way to either transliterate the characters or limit yourself only to languages written using the latin alphabet.
2. Use a web crawling algorithm to extract and index thousands of Wikipedia entries for each language. Those will be your corpora.
3. The parsing program, once you have the corpora, that should be the easy part, of course you would have to clean HTML tags and all that sort of data in order to get plain text in the language you are building the corpus for.
4. Obviously there are other considerations, example: vowels are often written using diptongs or special diacritical marks (that is why I mentioned that ideally the corpora should be encoded in the International Phonetic Alphabet, but no such corpora, that I know, are freely available). No easy solution here, only a trained linguist or somebody fully fluent in each of the languages could provide precise directions, although you could theoretically read about phonology articles for each language and get an idea."

https://www.quora.com/How-could-one-begin-to-calculate-what-are-the-most-commonly-used-consonants-and-vowels-across-all-languages/answer/Jos%C3%A9-A.-Ugalde/comment/13504362?__snids__=1391965547&__nsrc__=1&__filter__=all#comment13504661

**Comment by JoseUgalde** [comment]
Thank you for your re-post.

**Comment by masterkrang** [comment]
I believe this research was already done, check this out: 

http://web.phonetik.uni-frankfurt.de/upsid_info.html

cc @yhdaphne @JoseUgalde 

Here are some other related links. I believe @yhdaphne may have the resources to connect with the people at UCLA who did this research. I am not sure how accurate it is, would be good to confirm.

Related material:

http://www.linguistics.ucla.edu/faciliti/sales/software.htm#upsid

http://www.phonetics.ucla.edu/

Will close this and use these materials if we don't come up with a better plan to determine most widely used sounds.

**Comment by masterkrang** [comment]
consonant:  m   k   j   p   w   b   h   g   N   ?   n   s   tS  S   t   f   l   "n  "t  nj
in languages:   425 403 378 375 332 287 279 253 237 216 202 196 188 187 181 180 174 160 152 141
frequency:  94.2    89.4    83.8    83.2    73.6    63.6    61.9    56.1    52.6    47.9    44.8    43.5    41.7    41.5    40.1    39.9    38.6    35.5    33.7    31.3

vowel:  i   a   u   E   "o  "e  O   o   e   a~
in languages:   393 392 369 186 181 169 162 131 124 83
frequency:  87.1    86.9    81.8    41.2    40.1    37.5    35.9    29.0    27.5    18.4

**Comment by ghost** [comment]
The linguistics info from UCLA is just documentations of languages in the world, which is usually what traditional linguists does. I'm not sure how useful it could be in our project. However, I think we can make use of the stats that shows the sounds being used in the world languages and create a first set of sound inventory for "Kako", and see if it'd work, or not. 

Here is a test to create the sound inventory of Kako. I use onlyt the top 5 mostly used vowel sounds and 9 mostly used consonants in the world (circled in the IPA chart), based on the segment frequency on http://web.phonetik.uni-frankfurt.de/upsid_info.html. 

<img width="1077" alt="kako sound inventory" src="https://cloud.githubusercontent.com/assets/15071354/10573494/a782a844-7604-11e5-8370-f3ca0e8d1b90.png">

NEXT, syllable structure

Assuming that we want this language to have very simple syllabic structures, the simplest phonology/morphology can be: 
1.  Every word only has one syllable;
2.  A syllabic unit can be in one of the three structures: V, CV, CVC. 
For example,  
o   [o]   is a word in V structure.
pi  [pi]   is a word in CV structure.
pit [pit]  is a word in CVC structure. 

Then, roughly speaking (if the math were right), we will have (1_5) + (9_5) + (9_5_(9-2)) = 365 meaningful sound combinations**\* which can be used to create basic vocabulary of Kako. Since 365 is a very small number, we may have to play with other linguistic features/variables so that there will be much more vocabulary in Kako. #

**\* In the math I took away the possibility that the consonants [h] and [j] happen at the end of a word just because it seems hard to pronounce or to be heard.

I might make mistakes in these rough calculations, so feedback is welcome.

**Comment by masterkrang** [comment]
@yhdaphne are you suggesting that we should use V / CV and CVC? As opposed to V and CV (without CVC. Let me know yes / no and why?

**Comment by ghost** [comment]
@masterkrang : Yes and no. We can use only V and CV as well. It's just that incorporating only C and CV structures makes less the sound combinations. If less sound combinations is beneficial/efficient, of course we can adopt only V and CV and exclude CVC. 

If we only use V and CV, we will have 1_5 + 9_5 = 50 distinct sound combinations.

**Comment by JoseUgalde** [comment]
We are discussing the concept of language phonotactics...An example of a language with only CV and CVV combinations is Japanese (there's one exception, the phoneme 'N' is the only valid CVVC combination allowed).My opinion is that V / CV combinations provide an easier pronunciation.

Date: Mon, 19 Oct 2015 13:29:21 -0700

**Comment by masterkrang** [comment]
Let's move the V/CV/CVC discussion to this https://github.com/masterkrang/kako/issues/4

@JoseUgalde great mention of Phonotactics (new term for me), I am starting some research on phonotactics and phonemes so that I can get a superficial understand to possibly enhance our structure. This terminology should help us a lot when moving forward in discussion. 

As for the topic of discussion here, most used sounds... the research I have found was conducted across 451 world languages, I believe that having the most used 20 consonants and most used 10 vowels across all languages is a good place to start. I think we should probably just double check that this data isn't mangled or somehow inaccurate (unlikely, but just to be wise, probably should). 

If we have agreed that this is a good palette to start with, then I will close this issue. If there are any objections, they are welcome, but be quick :)

**Comment by ghost** [comment]
I think if we want to make Kako 1/10 of an existing language, maybe we can first look at English phonology. I’m not an expert in English phonology, but here is what I have. 

Reference: American English consonants and vowels https://en.wikipedia.org/wiki/English_phonology 

American English in general has 24 consonants and 11 vowels and 5(+1*) diphthongs, regardless how they are spelled in written English (excluding English dialects).
*Technically speaking, [oʊ] should be a diphthong but it is sometimes not pronounced as a real diphthong in English. Chinese [oʊ], as in 歐, is more like a diphthong. 

English sounds are listed in the chart here.
<img width="276" alt="english" src="https://cloud.githubusercontent.com/assets/15071354/10602723/e494d656-76ce-11e5-9e31-53200b8ae02b.png">
Source: http://www.ling.upenn.edu/~rnoyer/courses/103/Transcription.pdf 

And, regardless phonotactics, English has 19 possible syllable structures*: 
(English phonotactics: https://en.wikipedia.org/wiki/Phonotactics )
*This is part is based on what I learned in the past, not a theoretical account..
1.  V:  [ə], as in 'a' (may be the only example)
2.  VV:     [ɑɪ], as in 'I' or 'eye' (may be the only example)
3.  VC:             such as 'an' [ɑn], 'at' [æt]
4.  VCC:    such as ‘eggs’ [ɛgz]
5.  VCCC:   such as ‘inks’ [ɪŋks]
6.  VCCCC:  such as ‘elves’ [ɛlfθs]
7.  CVC:    such as 'cat' [kæt], 'bead' [bid]
8.  CVCC:   such as 'tax' [tæks]
9.  CVCCC:  such as 'taxed' [tækst]
10. CVCCCC: such as ‘selves’ [sɛlfθs]

(CCV: Seems not to have CCV structure)
11. CCVV:    such as 'stay' [steɪ]
12. CCVC:    such as 'step' [stɛp]
13. CCVCC:   such as 'stoned' [stɔnd]
14. CCVCCC: such as 'plants' [plænts]
15. CCVCCCC: such as ‘twelves’ [twɛlfθs]
16.   CCCV:        such as 'spree [spri]
17.   CCCVC:       such as 'spleen' [splin]
18.   CCCVCC:   such as 'splashed' [splæʃt]
19.   CCCVCCC: such as 'splints' [splɪnts]

So, if we want to make Kako simpler, we can reduce syllable structures of course. 

However, if we want to create a wordlist of root words first, it might be important to think the main/basic functions of using Kako as a communicative took. That is, whether Kako is expected to use in human mundane interaction, or in human-computer interaction.

**Comment by JoseUgalde** [comment]
I agree on the inventory of phonemes.

Date: Mon, 19 Oct 2015 17:45:28 -0700

**Comment by masterkrang** [comment]
ok i'm going to close this and just assuming that we are going to pull consonants and vowels from the sound research i've pasted here. for V CV and CVC etc we should refer to different threads that discuss that topic exclusively.
